# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d279d7e4f0b3762f531919f267bdd2605fc3219b5e1f3b5f160ba1e666ec92fc3eddde2ea3d93f7304b2c0ff2d2114db89dcb1cd40126c75071ee911781a270c

test:
  secret_key_base: 7b1f0252026cb6a25c9554042af6016539588fb75ebf8eaaf78a1e33ad3dadce308a8fee159f59d5797ed16df3cd5c67a893b34da2f38e2f60636b220e30f536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
